package generator

const (
	// File header
	genFileHeader = genFilePrefix + "%s\" from %s. DO NOT EDIT." // e.g.: Code generated by "xua server" from ./example/employee.go; DO NOT EDIT.
	serverCmd     = "server"
	genFilePrefix = "Code generated by \"xua "

	// Imports
	pkgEncodingJSON = "encoding/json"
	pkgFmt          = "fmt"
	pkgNetHTTP      = "net/http"
	pkgStrconv      = "strconv"
	pkgContext      = "context"

	pkgChi     = "github.com/go-chi/chi/v5"
	pkgZerolog = "github.com/rs/zerolog"

	// Tags
	tagRESTServer  = "http-server"
	tagHTTPCookie  = "http-cookies"
	tagHTTPHeader  = "http-headers"
	tagHTTPMethod  = "http-method"
	tagHTTPPrefix  = "http-prefix"
	tagHTTPPath    = "http-path"
	tagHTTPSuccess = "http-success"
	tagHTTPQuery   = "http-query"

	tagDelim = "|"

	// Server's service fields' suffixes
	suffixRESTField = "REST"

	// Default method values
	defaultSuccessCode = "200"
)
