// Code generated by "xua server" from example/employee.go; DO NOT EDIT.
package transport

import (
	"github.com/go-chi/chi/v5"
	"github.com/rs/zerolog"
)

type Server struct {
	log zerolog.Logger

	*chi.Mux

	employeeStorageREST *employeeStorageREST
}

func NewServer(log zerolog.Logger) *Server {
	server := &Server{
		log: log,
		Mux: chi.NewRouter(),
	}

	return server
}

